### ISSUE TITLE
ios xcode12 compilation issues

### ISSUE THREAD

**Issue by fjgal** [weplenish/flutter_wifi_connect#1]
Hi,

First, thanks for creating this plugins with minimal dependencies and using the latest Android APIs.

I found some issues while trying to use this plugin with Flutter 1.22.5 and xcode 12.3. The Swift code does not compile in my environment. Here are some of the problems:

* platform version in podspec file is pointing to `8.0` instead of `11.0`

```
   /flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.4/ios/Classes/SwiftFlutterWifiConnectPlugin.swift:15:16: error: 'disconnect()' is only available in iOS 11 or newer
            result(disconnect())
                   ^
    /flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.4/ios/Classes/SwiftFlutterWifiConnectPlugin.swift:15:16: note: add 'if #available' version check
            result(disconnect())
```

* missing argument labels

```
    /flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.4/ios/Classes/SwiftFlutterWifiConnectPlugin.swift:23:33: error: missing argument label 'arguments:' in call
            let args = GetArgs(call.arguments)
```

* return type in `connect` cannot be `Bool`

```
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_wifi_connect-0.0.4/ios/Classes/SwiftFlutterWifiConnectPlugin.swift:77:42: error: cannot convert return expression of type 'Void' to return type 'Bool'
        NEHotspotConfigurationManager.shared.apply(hotspotConfig) { [weak self] (error) in
```

* unhandled exception from `GetArgs`

I'm submitting a PR for your review which addresses the above issues. I tested it on iOS 14.2 and it seems to be working fine.

Thank you!

**Comment by vipero07** [comment]
merged the fixes
