### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by jcarvalhogo** [weplenish/flutter_wifi_connect#22]
Greetings everyone, I am trying to use the flutter wifi connect plugin, after many attempts I have not been successful

`E/flutter (12076): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, NetworkCallback was not registered, null, java.lang.IllegalArgumentException: NetworkCallback was not registered
E/flutter (12076): 	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4867)
E/flutter (12076): 	at com.weplenish.flutter_wifi_connect.FlutterWifiConnectPlugin.connect(FlutterWifiConnectPlugin.kt:329)
E/flutter (12076): 	at com.weplenish.flutter_wifi_connect.FlutterWifiConnectPlugin.onMethodCall(FlutterWifiConnectPlugin.kt:87)
E/flutter (12076): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (12076): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (12076): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (12076): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (12076): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (12076): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (12076): 	at android.os.Looper.loopOnce(Looper.java:226)
E/flutter (12076): 	at android.os.Looper.loop(Looper.java:313)
E/flutter (12076): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/flutter (12076): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12076): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/flutter (12076): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/flutter (12076): )
E/flutter (12076): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (12076): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (12076): <asynchronous suspension>
E/flutter (12076): #2      FlutterWifiConnect.connect (package:flutter_wifi_connect/flutter_wifi_connect.dart:36:29)
E/flutter (12076): <asynchronous suspension>
E/flutter (12076): #3      _WifiListPageState.loaderInfo (package:micro_app_qi5_prototyping/presentation/pages/wifi_list_page.dart:34:13)
E/flutter (12076): <asynchronous suspension>
E/flutter (12076): `

`    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
`

I added the bad permissions without success, could someone help me with this problem?

**Comment by vipero07** [comment]
I'm not entirely sure but there is another package that's continued to be updated. It is probably a better place to start. https://pub.dev/packages/plugin_wifi_connect
